### ISSUE TITLE
Not able to parse the html sitemaps

### ISSUE THREAD

**Issue by malhotraguy** [berkmancenter/mediacloud-ultimate-sitemap-parser#19]
Not able to parse html sitemaps.
For example tried for:  https://www.axa-im.com/site-map
![Screenshot from 2019-09-18 16-15-49](https://user-images.githubusercontent.com/34952205/65182607-a9499280-da2f-11e9-8aeb-84e69af84c0b.png)

**Comment by malhotraguy** [comment]
@pypt Linas have you noticed this bug ?

**Comment by pypt** [comment]
The module is not designed to parse HTML sitemaps, sorry. As per the README, module's concern is machine-parseable XML sitemaps that are commonly used by Google to be able to find all pages on a website and / or ingest Google News articles.
